kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongo-persistent-storage  
  labels:
    type: local
spec:
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/data01"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongo-persistent-storage-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi
---
apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: mongo
  name: mongo-controller
spec: 
  replicas: 1
  template:
    metadata:
      labels:
        name: mongo
    spec:
      containers:
      - image: mongo
        name: mongo
        ports:
        - name: mongo
          containerPort: 27017
          hostPort: 27017
        volumeMounts:
          - name: mongo-persistent-storage
            mountPath: /data/db
      volumes:
        - name: mongo-persistent-storage
          persistentVolumeClaim:
            claimName: mongo-persistent-storage-claim
---
apiVersion: v1
kind: Service
metadata:
  labels:
    name: mongo
  name: mongo
spec:
  ports:
    - port: 27017
      targetPort: 27017
  selector:
    name: mongo
---
apiVersion: apps/v1
kind: Deployment
metadata: 
  name: mybooks
  labels: 
    app: mybooks
spec:
  selector: 
    matchLabels:
      app: mybooks
  replicas: 1
  template: 
    metadata: 
      labels: 
        app: mybooks
    spec: 
      containers: 
      - image: mybooks:0.0.1-SNAPSHOT
        imagePullPolicy: Never
        name: mybooks
        ports: 
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mybooks
  labels:
    app: mybooks
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: mybooks
  type: LoadBalancer